version: '3'
services:
  database:
    restart: always
    image: amazon/dynamodb-local
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/
    volumes:
      - dynamodb_data:/home/dynamodblocal/data
    ports:
      - "8000:8000"
volumes:
  dynamodb_data:
    driver: local
