name: TW Node.js CI

on:
    # Trigger the workflow on push or pull request,
    # but only for the master branch
    push:
      branches:
        - master
    pull_request:
      branches:
        - master
    # Also trigger on page_build, as well as release created events
    page_build:
    release:
      types: # This configuration does not affect the page_build event above
        - created

jobs:
  unit_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        npm install
      working-directory: ./lib
    - run: |
        npm install
        npm run test:unit
        npm run build
        ls -la
        pwd
      working-directory: ./tw
    - name: Archive artifacts
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: ./tw/dist
    - name: Archive code coverage results
      uses: actions/upload-artifact@v1
      with:
        name: coverage
        path: tw/coverage